[tool.black]
line-length = 120
target-version = ['py310']
skip-string-normalization = true

[tool.mypy]
python_version = "3.10"
follow_imports = "skip"
ignore_missing_imports = true
strict_optional = true
disallow_subclassing_any = false
disallow_any_generics = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
