schema_version = "1.0.0"
id = "you_are_autosave"
version = "1.3.0"
name = "You Are Autosave"
tagline = "Show a warning when you haven't saved in a while"
maintainer = "Sybren Stüvel <sybren@blender.org>"
type = "add-on"
website = "https://github.com/sybrenstuvel/random-blender-addons"
tags = ["System"]
blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/*.webp",
  "/dist/",
  "go.mod",
  "go.sum",
  "mage.go",
  "/magefiles/",
]
